---
- name: "disable ipv6"
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1

- name: "install necessary packages"
  apt:
    name: "{{ item }}"
  with_items:
    - openvpn
    - modemmanager
    - ppp

- name: "ensure ppp0 interface config is in config file"
  blockinfile:
    dest: /etc/network/interfaces
    block: |
      auto ppp0
      iface ppp0 inet ppp
        pre-up sleep 10
        provider mobile

- name: "create necessary dirs"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/chatscripts
    - /etc/ppp/peers

- name: "copy ppp chatscripts to place"
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    directory_mode: yes
  with_items:
    - { src: etc/chatscripts/mobile.j2, dest: /etc/chatscripts/mobile }
    - { src: etc/ppp/chap-secrets.j2, dest: /etc/ppp/chap-secrets }
    - { src: etc/ppp/peers/mobile.j2, dest: /etc/ppp/peers/mobile }

- name: "add ifup ppp0 to /etc/rc.local"
  lineinfile:
    dest: /etc/rc.local
    insertbefore: exit 0
    line: ifup ppp0
